NAME	:=	ft_advanced_do-op
#HEADER	:=	$(wildcard *.h)
SRCS	:=	$(wildcard *.c)

CC	:=	gcc
CFLAGS	:=	-Wall -Werror -Wextra -I .
RM	:=	rm -f

#do-op	:	$(SRCS)
#		@$(CC) $(CFLAGS) $(HEADER) -o $(NAME) $(SRCS)

do-op	:	
		@$(CC) $(SRCS) -o $(NAME)
all	:	@$(NAME)
clean	:	
		@$(RM) $(NAME)
